### ISSUE TITLE
make slice size of the artboard instead of the bounds of artboard content

### ISSUE THREAD

**Issue by lostmonster** [DWilliames/export-artboards-sketch-plugin#1]
Currently, the plugin sets the slice bounds to the content of the artboard, and not the artboard itself. 

Could you change it so the slice extends to the bounds of the artboard, instead?

**Comment by DWilliames** [comment]
Thanks @lostmonster for the insight.

The intent is actually for the slice to be around the bounds of the artboard, not just the content within it — as you were after. So there must be a bug.

Can you please provide either a screenshot or a sketch file as an example of what you are talking about so that i can fix it :) 

Cheers

**Comment by lostmonster** [comment]
Surely. I'll attempt to recreate the issue. Does it work fine, for you?

**Comment by DWilliames** [comment]
Thanks. Yeah it seems to work fine of me in the testing I have done.

**Comment by DWilliames** [comment]
I was able to reproduce the issue, and it should be fixed now. Thanks
